### ISSUE TITLE
Can we hav event callback on clicking disabled dates

### ISSUE THREAD

**Issue by exexzian** [KennethanCeyer/pg-calendar#32]
It would be better if clicking on disabled date also calls callback where we can show info like _date disabled_

**Comment by exexzian** [comment]
One workaround I see is handling click event on this class `pignose-calendar-unit-disabled` .

Still just curious if pignose has native feature for this

**Comment by KennethanCeyer** [comment]
Hi @exexzian!

Sorry. It's a little late.

In this version, the feature you mentioned does not exist.

I think firing select event on even the disable button will cause confusion.

If you want to receive a response 

from the disable button, 

We will add the `click` event to the next version.

Thank you for ashking 👍

**Comment by exexzian** [comment]
thanks @KennethanCeyer for the response, yup as you mentioned firing event on disabled can confuse but at current that was just my use case.

As of now I will go with click event on `pignose-calendar-unit-disabled` and in the meantime wait for the next version is on 👍

**Comment by KennethanCeyer** [comment]
Hi @exexzian 

I update new version `v1.4.13` and that version has `click` callback option.

You can use as following code.

```javascript
$('.calendar').pignoseCalendar({
    click: function(event, context) {
        // this is clicked button.
        var $this = $(this);

        // event is general event object.
        console.log('Calendar information', context);
    }
});
```

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺

**Comment by exexzian** [comment]
@KennethanCeyer thanks for bringing the feature, however can we have look at the different options of click callback ?

**Comment by KennethanCeyer** [comment]
hello @exexzian 

I am so late...

Sorry about that 😢 

I will update whole documents related with #36 

Thank you.

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺

**Comment by KennethanCeyer** [comment]
Shortly

Click event listen only clicking event at date buttons (like jQuery's click event).

But select event catch date changes and pass the selected date at event parameter.

Thank you 😄

**Comment by KennethanCeyer** [comment]
Hi @mamtammak 

You can detailed information of click and select event to below link.

[Check this document](https://github.com/KennethanCeyer/pg-calendar/wiki/Documentation)

Thank you.
