### ISSUE TITLE
Customize Calendar For Persian Date?

### ISSUE THREAD

**Issue by mortezakarimi64** [KennethanCeyer/pg-calendar#35]
Hi.
Thank you for great calendar. Your calendar is limited in several languages. I want customize your calendar for Persian date. How can I do this? or How do I change your code? You use moment.latest.min.js in your project, How can i use moment-with-locales.min.js in your code? of course this is better idea your calendar as much as possible to support all languages that will be excellent but if you help me I would be very grateful.
Thank you a lot.

Note: Persian calendar is little different with other calendar. In Persian calendar first day of week is Saturday and last day of week is Friday. First 6 month is 31 days and 5 second month is 30 days. in last month depending on whether it is a leap year or not, days can be 30 days or 29 days (If leap year --> 30 days, else 29 days).

**Comment by KennethanCeyer** [comment]
Hi @mortezakarimi64 

PIGNOSE Calendar doesn't easy to customize the new language. (The structure issue.)

If you okay i will update its structure.

Also i can add Persian language if you join the contributor.

Just fill below format

```javascript
weeks: {
	en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], // an example
	fa: ['', '', '', '', '', '', ''],
},
monthsLong: {
	en: ['January', 'February', 'March', 'April', 'May', 'Jun', 'July', 'August', 'September', 'October', 'November', 'December'], // an example
	fa: ['', '', '', '', '', '', '', '', '', '', '', ''],
},
months: {
	en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], // an example
	fa: ['', '', '', '', '', '', '', '', '', '', '', ''],
}
```

Thank you, I will update as soon as possible.

**Comment by KennethanCeyer** [comment]
If you need to quick fix.

Please follow to read [Language](https://github.com/KennethanCeyer/PIGNOSE-Calendar/wiki/Language) section.

This feature is available at `v1.4.14`.

**Comment by mortezakarimi64** [comment]
Hi @KennethanCeyer.
Thank you so much for your attention. 
Names of months and days of the week in the Persian calendar is as follows:
```
weeks: {
	en: ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'], // an example
	fa: ['شنبه', 'آدینه', 'پنج', 'چهار', 'سه', 'دو', 'یک'],
},
monthsLong: {
	en: ['January', 'February', 'March', 'April', 'May', 'Jun', 'July', 'August', 'September', 'October', 'November', 'December'], // an example
	fa: ['آذر', 'آبان', 'مهر', 'شهریور', 'مرداد', 'تیر', 'خرداد', 'اردیبهشت', 'فروردین', 'اسفند', 'بهمن', 'دی'],
},
months: {
	en: ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'], // an example
	fa: ['آذر', 'آبان', 'مهر', 'شهریور', 'مرداد', 'تیر', 'خرداد', 'اردیبهشت', 'فروردین', 'اسفند', 'بهمن', 'دی'],
}
```

**Comment by KennethanCeyer** [comment]
Hi @mortezakarimi64! 

Thank you for your quick reply. 

It's good format to add language. 

I will update this language to next version(maybe tommorow) 

And you will be registered among contributors. 

By the way i am replying via mobile in bus. 

I hope you to understand about a typo.

**Comment by mortezakarimi64** [comment]
Hi @KennethanCeyer 
I'm sorry for the delay in response. I was at the weekend. Thank a lot.

**Comment by KennethanCeyer** [comment]
Hi @mortezakarimi64 

I am so sorry about delayed your request.

I will update new patch `v1.4.15`.

Thank you 👍

**Comment by mortezakarimi64** [comment]
Hi @KennethanCeyer 
I fix some item in css and js.
Persian calendar is rtl language, so i change your css and you forgot to add 'fa' to 'supports'. also i have changed the location of the next and previous buttons. It seems the days of the week were reversed in js due to 'github editor'. I have attached the modified files. 
But there is still a point:
In Persian calendar first 6 month is 31 days and 5 second month is 30 days. in last month depending on whether it is a leap year or not, days can be 30 days or 29 days (If leap year --> 30 days, else 29 days). First month of year is 'فروردین' and last month of year is 'اسفند'. 
1st of January is 11st of 'دی'.
Gregorian and Persian calendar have 10 days difference with each other.
I hope I explained things well.

`<style type="text/css">

        .pignose-calendar .pignose-calendar-header .pignose-calendar-week { float:right; }
        .pignose-calendar-unit { float:right; }
        .pignose-calendar .pignose-calendar-header .pignose-calendar-week.pignose-calendar-week-sun, 
        .pignose-calendar .pignose-calendar-header .pignose-calendar-week.pignose-calendar-week-sat { color:rgba(0,0,0,.87);}
        .pignose-calendar .pignose-calendar-header .pignose-calendar-week.pignose-calendar-week-fri { color: #fa4832; }
        .pignose-calendar-unit.pignose-calendar-unit-sun a, .pignose-calendar-unit.pignose-calendar-unit-sat a { color: #3abbb9; }
        .pignose-calendar-unit.pignose-calendar-unit-fri a { color: #fa4832; }
        .pignose-calendar .pignose-calendar-top .pignose-calendar-top-nav.pignose-calendar-top-prev { float:right; margin-right: 1.6em; margin-left:0; }
        .pignose-calendar .pignose-calendar-top .pignose-calendar-top-nav.pignose-calendar-top-next { float:left; margin-left: 1.6em; margin-right:0; }
    </style>`
```
supports: ['en', 'ko', 'fr', 'ch', 'de', 'jp', 'pt', 'da', 'pl', 'es', 'fa'],
weeks: 
{
  fa: ['یک', 'دو', 'سه', 'چهار', 'پنج', 'آدینه', 'شنبه'],
},
monthsLong: {
 fa: ['دی', 'بهمن', 'اسفند', 'فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر'],
},
months: {
 fa: ['دی', 'بهمن', 'اسفند', 'فروردین', 'اردیبهشت', 'خرداد', 'تیر', 'مرداد', 'شهریور', 'مهر', 'آبان', 'آذر'],
}
```
[calendar.docx](https://github.com/KennethanCeyer/PIGNOSE-Calendar/files/957808/calendar.docx)

**Comment by KennethanCeyer** [comment]
I noticed this issue today.

I will re-open this issue and update this comment with next version.

Thank you 👍

**Comment by parhamin2010** [comment]
hey, Is it possible to use this calender for jalali solar system instead of georgia calendar becuase it has alot of problem for calculating in these system like day of month
