### ISSUE TITLE
date range includes date disabled

### ISSUE THREAD

**Issue by acipolla** [KennethanCeyer/pg-calendar#36]
It is possible to not permit the selection of a date range if includes a date disabled?
thank you

**Comment by KennethanCeyer** [comment]
Hi @acipolla 

PIGNOSE Calendar's default option is not allowed to select among the disabled dates.

So you can deny to select a date range that includes disabled dates.

However if you don't want this feature,

You can give `over` option like as follows.

```javascript
$('.calendar-selector').pignoseCalendar({
  multiple: true,
  over: true
});
```

`over` option allows to select the date range, even if it includes disable dates.

Thank you!!~

**Comment by acipolla** [comment]
thank you!!!
I was not able to find the over property, where could I find a complete list of property and events (I was looking for onmonthchange event to upload the disable dates via json)?

**Comment by KennethanCeyer** [comment]
Hello @acipolla

I will fully update the document at tonight.

I hope this plan is done within a day.

**Comment by acipolla** [comment]
thank you!!!
