### ISSUE TITLE
Multiple with disabled ranges

### ISSUE THREAD

**Issue by slon-org-ua** [KennethanCeyer/pg-calendar#37]
Hey,

I have a "rangeDate is not defined" with options below

`minDate: new Date(),
disabledRanges: disabledRanges,
format: 'DD.MM.YYYY',
multiple: true,`

disabledRanges — array [ [], [] ... [] ]

How I can to fix it?

**Comment by slon-org-ua** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Undeclared_var
I have fixed it.

**Comment by KennethanCeyer** [comment]
Hello @slon-org-ua 

I am very sorry about the late reply.

"rangeDate is not defined" message will be occurred when one of item in the disabledRange is undefined.

I am really glad you solved the problem.

Thank you @slon-org-ua!
