### ISSUE TITLE
Custom CSS and positioning

### ISSUE THREAD

**Issue by jdrsqrd** [KennethanCeyer/pg-calendar#38]
What is the best way to apply custom CSS (line heights, spacing, colors, and positioning) without having to write a WHOLE custom css?

Also I'm trying to position the calendar so it floats to the right or left but the width gets messed up. (I've tried putting it inside a holder div but same issues)

**Comment by KennethanCeyer** [comment]
Hello @jdrsqrd 

I am writing a guideline for customize styles.

Please wait a moment.

Thank you.

**Comment by KennethanCeyer** [comment]
https://github.com/KennethanCeyer/pg-calendar/wiki/Styles

This is style guideline.

The wrapper of calendar is set `max-width: 360px;`

So, if you need to add `float` property at the calendar.

You must declared specified width on that calendar.

**Comment by jdrsqrd** [comment]
Thanks!

**Comment by KennethanCeyer** [comment]
This issue will be closed tomorrow.

If you have other issues, Please create a new issue 🍺
