### ISSUE TITLE
want to use previous and next button 

### ISSUE THREAD

**Issue by mamtammak** [KennethanCeyer/pg-calendar#39]
Hi ,
I am a new user to Pignose calendar api , I want to trigger previous and next button and write custom code on that , how can i do that.

**Comment by KennethanCeyer** [comment]
Hello @mamtammak 

The callback for arrow buttons is not developed yet.

I will try to update the version on today.

Thank you.

**Comment by mamtammak** [comment]
hi , sorry for asking again
but have the callback for arrow buttons updated ?
so that i can use them.

**Comment by KennethanCeyer** [comment]
Hi @mamtammak 

You can detailed information of new events to below link.

[Check this document](https://github.com/KennethanCeyer/pg-calendar/wiki/Documentation)

Thank you.
