### ISSUE TITLE
Italian traslation

### ISSUE THREAD

**Issue by acipolla** [KennethanCeyer/pg-calendar#40]
weeks: {
  it: ['Dom', 'Lun', 'Mar', 'Mer', 'Gio', 'Ven', 'Sab'],
},
monthsLong: {
  it: ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'],
},
months: {
  it: ['Gen', 'Feb', 'Mar', 'Apr', 'Mag', 'Giu', 'Lug', 'Ago', 'Set', 'Ott', 'Nov', 'Dic'],
}

**Comment by KennethanCeyer** [comment]
Hello @acipolla 

Thank you for your contribution!

I will include this language in next version.

Thank you again!

**Comment by KennethanCeyer** [comment]
This issue is related #35

**Comment by KennethanCeyer** [comment]
This issue was fixed at `v1.4.20`.

If you have any another issue.

Please make by a new issue.

Thank you for sending a issue :smile.

**Comment by KennethanCeyer** [comment]
Hi @acipolla.

Your profile is registered at [README.md](https://github.com/KennethanCeyer/pg-calendar/blob/master/README.md) as contributor.

Thank you for your contribution.
