### ISSUE TITLE
Get Calendar passing particular month and year.

### ISSUE THREAD

**Issue by mamtammak** [KennethanCeyer/pg-calendar#42]
Hi ,

I want to call particular month and year calendar , is it possible to do that using pignose calendar

**Comment by vineetkulkarni016** [comment]
@mamtammak Even I was finding the same. But there are no options which can get that job done as of now.Hope contributors address this issue soon!!!!!

**Comment by KennethanCeyer** [comment]
Hi @mamtammak 

If you want to set each other the initial date to the calendars.

Shortly you can give `date` option, This option can helps to set the date when they initialized.

Thank you 👍
