### ISSUE TITLE
Spelling mistake in German translation

### ISSUE THREAD

**Issue by dominikdassow** [KennethanCeyer/pg-calendar#43]
The short version of the first German month is **not** `Jän`. It is `Jan`.

**Comment by KennethanCeyer** [comment]
Hi @dominikdassow 

I am sorry i'm late.

It will be fixed the next version.

Thank you 😄

**Comment by KennethanCeyer** [comment]
This issue was fixed at `v1.4.20`.

If you have any another issue.

Please make by a new issue.

Thank you for sending a issue :smile.
