### ISSUE TITLE
Multiple Weeks only works from Sunday ? 

### ISSUE THREAD

**Issue by Hoinzey** [KennethanCeyer/pg-calendar#44]
So I have the following  options set to select a week at a time, and also for my weeks to start from a Monday, not a Sunday.

week:1,
pickWeeks:true,
multiple:true,

But if I select a week it still starts from the Sunday instead of the Monday. Giving a screenshot.
![screenshot_20170712_171523](https://user-images.githubusercontent.com/19781690/28127835-bb30323a-6725-11e7-86e8-d8d11dfaf5ca.png)

**Comment by KennethanCeyer** [comment]
Ah. I think it seems some bugs.

I will fix this problem right now. (Concentration)

Thank you @Hoinzey.

**Comment by KennethanCeyer** [comment]
This issue was fixed at `v1.4.20`.

If you have any another issue.

Please make by a new issue.

Thank you for sending a issue :smile.
