### ISSUE TITLE
Bold the dates with different colors in schedule calendar

### ISSUE THREAD

**Issue by vinay1243** [KennethanCeyer/pg-calendar#45]
I have to bold the dates in the schedule calendar instead of circles in the bottom.
Please let know how can i  customize it.

**Comment by kwek92** [comment]
`.pignose-calendar.pignose-calendar-blue .pignose-calendar-body .pignose-calendar-row .pignose-calendar-unit.pignose-calendar-unit-active a{
    color: #5c6270 ;
    background-color: transparent ;
    box-shadow: none ;
}

.pignose-calendar .pignose-calendar-unit.pignose-calendar-unit-active a{
font-weight: 900 ;
background-color: transparent ;
box-shadow: none ;
}`

**Comment by kwek92** [comment]
.pignose-calendar.pignose-calendar-blue .pignose-calendar-body .pignose-calendar-row .pignose-calendar-unit.pignose-calendar-unit-active a{
    color: #5c6270 ;
    background-color: transparent ;
    box-shadow: none ;
}

.pignose-calendar .pignose-calendar-unit.pignose-calendar-unit-active a{
font-weight: 900 ;
background-color: transparent ;
box-shadow: none ;
}

**Comment by KennethanCeyer** [comment]
Hi @vinay1243 

Did you solve this question?

If it is, I will close this issue.

And thank you for answering @kwek92 👍

**Comment by vinay1243** [comment]
Hi @kwek92 ,

I want the schedule event dates to be bold in color. Currently if a date has schedule it will have have small circle below that date. I don't want circle in down, instead the date has to bold in the specified color.

![calendar](https://user-images.githubusercontent.com/20223728/29973178-395dc17e-8f4c-11e7-9b2c-d6a11622893c.png)

In the above screen shot it has circle below the schedule. Instead of circle just bold that date.

**Comment by Buterflies** [comment]
Can someone help me write  CSS to change the weekday and highlight colours on my calendar?
