### ISSUE TITLE
Pignose calendar + input = ReferenceError: models is not defined

### ISSUE THREAD

**Issue by OinkEsFabuloso** [KennethanCeyer/pg-calendar#47]
Hi!

When relating a calendar with an input as:

`<input type="text" id="text-calendar" class="calendar" />`

`$(function() {`
`    $('input.calendar').pignoseCalendar({`
`		modal: true,`
`		format: 'YYYY-MM-DD' // date format string. (2017-02-02)`
`	});`
`});`

I the user clicks on the input text box, pignose's modal appears, the user can now choose a date and the date is written into the input text box. So far so good.

If the user decides he wants a different date, if he clicks again on the input text box nothing happens. The Javascript console shows the following error message:

**ReferenceError: models is not defined**

This is true even in the example title **Input type** provided at:
https://www.pigno.se/barn/PIGNOSE-Calendar/

Is this the expected behaviour?

Thanks!

**Comment by KennethanCeyer** [comment]
Hi @OinkEsFabuloso 

I understand the issue that you mentioned And noticed this error message in the demo page.

I will fix this issue within today.

Thank you.

**Comment by KennethanCeyer** [comment]
Hi @OinkEsFabuloso  again 😄 
The issue is fixed at `v1.4.22` version.
I will add automation testing for preventing recurrence these errors (including e2e)
Thank you.

**Comment by OinkEsFabuloso** [comment]
Thanks!! Works like a charm 👍
