### ISSUE TITLE
Initialized parameter doesn't work

### ISSUE THREAD

**Issue by OinkEsFabuloso** [KennethanCeyer/pg-calendar#48]
Hi,

I'm trying to create a calendar without an initialized (selected) date. According to the documentation
(https://github.com/KennethanCeyer/pg-calendar/wiki/Documentation):

> **initialized**
> If this option is false, Calendar doesn't display active date at first time.
> type: boolean
> default: true
> example:
> `$('.calendar').pignoseCalendar({`
> `    initialized: false `
> `});`

I've looked into Pignose's code and it seems that the option is called **initialize** (without the final "d"). There's an error in the documentation.

Cheers,
  Oink!

**Comment by KennethanCeyer** [comment]
Hi @OinkEsFabuloso 

Thank you for reporting issue

It is expected to be confirmed after 7 o'clock. (what a busy day..!)

Thank you 😄

**Comment by KennethanCeyer** [comment]
@OinkEsFabuloso ahh! `initialized` option is named `initialize`

i didn't expected the typo

it will be replaced `initialized` to next version.

**Comment by KennethanCeyer** [comment]
this issue is fixed right now `v1.4.23`

thank you :smile

**Comment by disapamok** [comment]
Please update this on your documentation. I ran so many pages to find this. ;-) 
Thank you. 😄
