### ISSUE TITLE
Button labels "OK" and "Cancel" are hardcoded in English.

### ISSUE THREAD

**Issue by TurtleKitty** [KennethanCeyer/pg-calendar#54]
Internationalization seems to work well in Pignose, with the exception of these two buttons; their values are hardcoded on lines 47 and 48 of `src/js/methods/init.js`.

![image](https://user-images.githubusercontent.com/593081/32524714-a9a0e19a-c3e6-11e7-9aaa-e35ae6f5d547.png)

**Comment by KennethanCeyer** [comment]
This feature is added version `v1.4.26`

check the line as follows

https://github.com/KennethanCeyer/pg-calendar/commit/3a2be454573c8de3435d1ccd60d565b1b07d93b4#diff-a49f6b99ae95f163b52e14f1520d2b6fR47
