### ISSUE TITLE
Js error: moment is not defined

### ISSUE THREAD

**Issue by nok91** [KennethanCeyer/pg-calendar#55]
pignose.calendar.js:sourcemap:17 Uncaught ReferenceError: moment is not defined

**Comment by KennethanCeyer** [comment]
you need to `moment` library

If you use `pignose.calendar.full.min.js`

This issue will be solved

or you can try to install `moment` library directly

```bash
$ npm install moment --save
```

**Comment by KennethanCeyer** [comment]
ah.. `full.min.js` seems some moduling issue..

you can use by including `momnet.js` library

or you can download `v1.4.24` and use `pg-calendar.full.min.js`

Thank you 😄

**Comment by nok91** [comment]
Thanks!!
