### ISSUE TITLE
keep settings when using method

### ISSUE THREAD

**Issue by lizuka** [KennethanCeyer/pg-calendar#76]
I'm using your calendar to filter markers on a Google Map. Works great. 
But if I want to reset the map or select specific dates from an external button I have to redeclare every option and callbacks.

```
$('#pignoseCal').pignoseCalendar({
	lang: 'fr',
	week: 1,
	date: moment('2018-06-01'),
	format: 'YYYYMMDD',
	multiple: true,
	initialize: false,
	minDate: '20180601',
	maxDate: '20180622',
	select: function(date, context){
	// I removed these lines to shorten my post. It basically filters the map depending on selected dates
	}
});
```

When I call this method : 
```
$('#allDates').on( 'click', function() {
	$('#pignoseCal').pignoseCalendar({
		set: function(date){ moment('2018-06-01')}
	} );
});
```
I lose all my previous configuration. Am I missing something?

**Comment by dalemcbeath** [comment]
same here.  I simply want to have the calendar move to a date (today in my case) without loosing any of the other settings.  I have not found a way to do this other than storing everything and re-initializing the cal.  I suspect that the configure method should allow this, but nothing I try works at all.

`$('#basic').pignoseCalendar({date: moment() } );`

takes the calendar to 'today' but looses everything else.

`$('#basic').pignoseCalendar('configure', {date: moment() } );`

doesn't do anything.

on the other hand, everything else works wonderfully !  thank you for this plugin.

**Comment by dwhiting10** [comment]
> I'm using your calendar to filter markers on a Google Map. Works great.
> But if I want to reset the map or select specific dates from an external button I have to redeclare every option and callbacks.
> 
> ```
> $('#pignoseCal').pignoseCalendar({
> 	lang: 'fr',
> 	week: 1,
> 	date: moment('2018-06-01'),
> 	format: 'YYYYMMDD',
> 	multiple: true,
> 	initialize: false,
> 	minDate: '20180601',
> 	maxDate: '20180622',
> 	select: function(date, context){
> 	// I removed these lines to shorten my post. It basically filters the map depending on selected dates
> 	}
> });
> ```
> 
> When I call this method :
> 
> ```
> $('#allDates').on( 'click', function() {
> 	$('#pignoseCal').pignoseCalendar({
> 		set: function(date){ moment('2018-06-01')}
> 	} );
> });
> ```
> 
> I lose all my previous configuration. Am I missing something?

Try using the 'set' method if all you want to do is dynamically set a date but keep all the rest of your config:
`$('#pignoseCal').pignoseCalendar('set', moment('2018-06-01').format('YYYY-MM-DD'));`

**Comment by lizuka** [comment]
Thanks, I will test this.
